[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube          ; HAL 库（不是 Arduino、不是标准库）
upload_protocol = stlink       ; 烧录：pio run -t upload（ST-Link 四线）
debug_tool = stlink            ; 可选：pio debug 单步调试
monitor_speed = 115200
build_flags =                  ; 让各模块之间能互相 include
  -Isrc/Hardware
  -Isrc/System
  -Isrc/freertos